version: '3.7'

services:
  asterisk.cr:
    build:
      context: .
      dockerfile: Dockerfile-16
    # ports:
    #   - 0.0.0.0:18080:8080
    # depends_on:
    #   - redis
    #   - asterisk
    volumes:
      - .:/src

  "13":
    build:
      context: .
      dockerfile: Dockerfile-13
    volumes:
      - .:/src

  # redis:
  #   image: redis:alpine
  #
  # api:
  #   image: andrius/alpine-webrick
  #
  # asterisk:
  #   image: andrius/asterisk
  #   environment:
  #     - ASTERISK_SIP_PORT=5062
